import { printToFileAsync } from 'expo-print';
import { shareAsync } from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';
import { APP_CONFIG } from '../constants';

export const generateFIRPDF = async (fir) => {
  // ── Convert local plate photo to base64 data URI so it renders in the PDF ──
  // expo-print's WebView renderer cannot access file:// URIs — only data: URIs work.
  // Strategy: copy to permanent app dir first (cache URIs can vanish), then read as base64.
  let platePhotoDataUri = null;
  if (fir.platePhotoUri) {
    try {
      console.log('[PDF] Plate photo original URI:', fir.platePhotoUri);

      // Step 1: ensure the source file exists
      const info = await FileSystem.getInfoAsync(fir.platePhotoUri);
      console.log('[PDF] Plate photo file info:', JSON.stringify(info));

      if (info.exists) {
        // Step 2: copy to permanent document directory so it doesn't get GC'd
        const destDir  = FileSystem.documentDirectory + 'sahaas_evidence/';
        const destPath = destDir + `plate_${Date.now()}.jpg`;
        await FileSystem.makeDirectoryAsync(destDir, { intermediates: true }).catch(() => {});
        await FileSystem.copyAsync({ from: fir.platePhotoUri, to: destPath });

        // Step 3: read as base64
        const base64 = await FileSystem.readAsStringAsync(destPath, {
          encoding: FileSystem.EncodingType.Base64,
        });
        platePhotoDataUri = `data:image/jpeg;base64,${base64}`;
        console.log(`[PDF] ✅ Plate photo embedded as base64 (${Math.round(base64.length / 1024)} KB)`);
      } else {
        console.warn('[PDF] ⚠️ Plate photo file does not exist at URI:', fir.platePhotoUri);
      }
    } catch (e) {
      console.error('[PDF] ❌ Plate photo base64 failed:', e.message, e);
    }
  }

  const evidenceWithVideo = [
    ...(fir.evidenceList || []),
    (fir.videoUri || fir.videoUrl)
      ? `📹 Incident Video Recording${fir.videoUrl ? ` — ${fir.videoUrl}` : ''} — ${fir.incidentTime}`
      : null,
    fir.platePhotoUri
      ? '📸 Vehicle Number Plate Photo — High-resolution capture (see evidence section below)'
      : null,
  ].filter(Boolean);

  const videoFileName = fir.referenceNumber
    ? `SAHAAS_${fir.referenceNumber.replace(/[^A-Z0-9]/gi, '_')}.mp4`
    : 'SAHAAS_incident_video.mp4';

  try {
    const { uri } = await printToFileAsync({
      html: buildFIRHTML({
        ...fir,
        evidenceList: evidenceWithVideo,
        videoFileName,
        // platePhotoDataUri = base64 data URI (null if conversion failed)
        // Keep original hasPlatePhoto so the block always shows when photo was taken
        platePhotoDataUri,
        // Override platePhotoUri with data URI for img src (null = no img tag)
        platePhotoUri: platePhotoDataUri,
      }),
      base64: false,
    });
    return uri;
  } catch (error) {
    console.error('PDF generation error:', error);
    throw error;
  }
};

export const shareFIRPDF = async (uri) => {
  await shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: 'Share / Download FIR PDF',
    UTI: 'com.adobe.pdf',
  });
};

// ── Language label maps ──────────────────────────────────────────────────────
const LABELS = {
  en: {
    title: 'FIRST INFORMATION REPORT',
    subtitle: 'TELANGANA POLICE — AI-POWERED INCIDENT RESPONSE',
    overview: '📋 Incident Overview',
    location: '📍 Location Details',
    details: '🚗 Incident Details',
    timeline: '⏱️ Timeline',
    statement: '📝 Complainant\'s Statement',
    sections: 'Sections Applicable',
    evidence: '🎥 Evidence List',
    ai: '🤖 AI Analysis & Insights',
    generated: 'Generated by SAHAAS SOTE AI on',
    videoTitle: '📹 Video Evidence — Click to Play',
    plateTitle: '📸 Number Plate Photo Evidence',
    incidentType: 'Incident Type',
    dateTime: 'Date & Time',
    severity: 'Severity Level',
    summary: 'Incident Summary',
    address: 'Address',
    gps: 'GPS Coordinates',
    maps: 'Google Maps',
    injuries: 'Injuries Reported',
    vehicle: 'Vehicle Number',
    people: 'People Involved',
    witnesses: 'Witnesses',
    videoFile: 'Video File',
    playBtn: 'TAP / CLICK TO PLAY INCIDENT VIDEO',
    playLabel: '▶ PLAY',
    copyUrl: '📋 Video URL (copy & open in browser if tap doesn\'t work)',
    permanent: '✅ Free permanent link — plays unlimited times, never expires',
    evidenceNote: '📌 Evidence Note:',
    geoTagged: 'GEO-TAGGED', timestamped: 'TIMESTAMPED', aiVerified: 'AI VERIFIED', online: 'ONLINE ∞',
    firRef: 'FIR Reference Number',
    digital: 'Digital Signature: AI Verified',
    submitted: 'Submitted via:',
    policeFooter: 'Telangana State Police | Emergency AI Response System',
    firSubmitted: 'FIR SUBMITTED TO POLICE STATION',
  },
  hi: {
    title: 'प्रथम सूचना रिपोर्ट (FIR)',
    subtitle: 'तेलंगाना पुलिस — AI संचालित घटना प्रतिक्रिया',
    overview: '📋 घटना सारांश',
    location: '📍 स्थान विवरण',
    details: '🚗 घटना विवरण',
    timeline: '⏱️ समयरेखा',
    statement: '📝 शिकायतकर्ता का बयान',
    sections: 'लागू धाराएं',
    evidence: '🎥 साक्ष्य सूची',
    ai: '🤖 AI विश्लेषण और अंतर्दृष्टि',
    generated: 'SAHAAS SOTE AI द्वारा उत्पन्न',
    videoTitle: '📹 वीडियो साक्ष्य — चलाने के लिए क्लिक करें',
    plateTitle: '📸 नंबर प्लेट फोटो साक्ष्य',
    incidentType: 'घटना का प्रकार',
    dateTime: 'दिनांक और समय',
    severity: 'गंभीरता स्तर',
    summary: 'घटना सारांश',
    address: 'पता',
    gps: 'GPS निर्देशांक',
    maps: 'Google मानचित्र',
    injuries: 'चोटें रिपोर्ट हुईं',
    vehicle: 'वाहन नंबर',
    people: 'शामिल लोग',
    witnesses: 'गवाह',
    videoFile: 'वीडियो फ़ाइल',
    playBtn: 'घटना वीडियो चलाने के लिए टैप करें',
    playLabel: '▶ चलाएं',
    copyUrl: '📋 वीडियो URL (ब्राउज़र में कॉपी करें)',
    permanent: '✅ स्थायी लिंक — असीमित बार चलाएं',
    evidenceNote: '📌 साक्ष्य नोट:',
    geoTagged: 'जियो-टैग्ड', timestamped: 'टाइमस्टैम्प्ड', aiVerified: 'AI सत्यापित', online: 'ऑनलाइन ∞',
    firRef: 'FIR संदर्भ संख्या',
    digital: 'डिजिटल हस्ताक्षर: AI सत्यापित',
    submitted: 'प्रस्तुत:',
    policeFooter: 'तेलंगाना राज्य पुलिस | आपातकालीन AI प्रतिक्रिया प्रणाली',
    firSubmitted: 'FIR पुलिस स्टेशन में जमा की गई',
  },
  te: {
    title: 'ప్రథమ సమాచార నివేదిక (FIR)',
    subtitle: 'తెలంగాణ పోలీసు — AI ఘటన స్పందన',
    overview: '📋 ఘటన వివరాలు',
    location: '📍 స్థాన వివరాలు',
    details: '🚗 ఘటన వివరాలు',
    timeline: '⏱️ సమయ వరుస',
    statement: '📝 ఫిర్యాదీ వాంగ్మూలం',
    sections: 'వర్తించే సెక్షన్లు',
    evidence: '🎥 సాక్ష్యాల జాబితా',
    ai: '🤖 AI విశ్లేషణ',
    generated: 'SAHAAS SOTE AI ద్వారా రూపొందించబడింది',
    videoTitle: '📹 వీడియో సాక్ష్యం',
    plateTitle: '📸 నంబర్ ప్లేట్ ఫోటో సాక్ష్యం',
    incidentType: 'ఘటన రకం',
    dateTime: 'తేదీ & సమయం',
    severity: 'తీవ్రత స్థాయి',
    summary: 'ఘటన సారాంశం',
    address: 'చిరునామా',
    gps: 'GPS అక్షాంశాలు',
    maps: 'Google Maps',
    injuries: 'గాయాలు నివేదించబడ్డాయి',
    vehicle: 'వాహన నంబర్',
    people: 'పాల్గొన్న వ్యక్తులు',
    witnesses: 'సాక్షులు',
    videoFile: 'వీడియో ఫైల్',
    playBtn: 'వీడియో చూడడానికి టాప్ చేయండి',
    playLabel: '▶ చూడండి',
    copyUrl: '📋 వీడియో URL',
    permanent: '✅ శాశ్వత లింక్',
    evidenceNote: '📌 సాక్ష్య గమనిక:',
    geoTagged: 'జియో-ట్యాగ్డ్', timestamped: 'టైమ్‌స్టాంప్డ్', aiVerified: 'AI ధృవీకరించబడింది', online: 'ఆన్‌లైన్ ∞',
    firRef: 'FIR సూచన సంఖ్య',
    digital: 'డిజిటల్ సంతకం: AI ధృవీకరించబడింది',
    submitted: 'సమర్పించబడింది:',
    policeFooter: 'తెలంగాణ రాజ్య పోలీసు | AI స్పందన వ్యవస్థ',
    firSubmitted: 'FIR పోలీస్ స్టేషన్‌కు సమర్పించబడింది',
  },
  gu: {
    title: 'પ્રથમ માહિતી અહેવાલ (FIR)',
    subtitle: 'તેલંગાણા પોલીસ — AI સ્વચ્ચ ઘટના પ્રતિભાવ',
    overview: '📋 ઘટના વિહંગાવલોકન',
    location: '📍 સ્થળ વિગતો',
    details: '🚗 ઘટના વિગતો',
    timeline: '⏱️ ઘટના ક્રમ',
    statement: '📝 ફરિયાદીનું નિવેદન',
    sections: 'લાગુ કલમો',
    evidence: '🎥 પુરાવા સૂચિ',
    ai: '🤖 AI વિશ્લેષણ',
    generated: 'SAHAAS SOTE AI દ્વારા જનરેટ',
    videoTitle: '📹 વિડિઓ પુરાવો',
    plateTitle: '📸 નંબર પ્લેટ ફોટો પુરાવો',
    incidentType: 'ઘટનાનો પ્રકાર',
    dateTime: 'તારીખ અને સમય',
    severity: 'ગંભીરતા સ્તર',
    summary: 'ઘટના સારાંશ',
    address: 'સરનામું',
    gps: 'GPS કોઓર્ડિનેટ',
    maps: 'Google Maps',
    injuries: 'ઈજા નોંધાઈ',
    vehicle: 'વાહન નંબર',
    people: 'સામેલ લોકો',
    witnesses: 'સાક્ષીઓ',
    videoFile: 'વિડિઓ ફાઈલ',
    playBtn: 'ઘટના વિડિઓ ચલાવવા ટૅપ કરો',
    playLabel: '▶ ચલાવો',
    copyUrl: '📋 વિડિઓ URL',
    permanent: '✅ કાયમી લિંક',
    evidenceNote: '📌 પુરાવા નોંધ:',
    geoTagged: 'જીઓ-ટેગ્ડ', timestamped: 'ટાઈમ-સ્ટેમ્પ', aiVerified: 'AI ચકાસાયેલ', online: 'ઓનલાઈન ∞',
    firRef: 'FIR સંદર્ભ નંબર',
    digital: 'ડિજિટલ સહી: AI ચકાસાયેલ',
    submitted: 'સબમિટ:',
    policeFooter: 'તેલંગાણા રાજ્ય પોલીસ | AI ઘટના પ્રતિભાવ',
    firSubmitted: 'FIR પોલીસ સ્ટેશનમાં સબમિટ',
  },
};

// ── Severity stage config ────────────────────────────────────────────────────
const SEVERITY_STAGES = ['Low', 'Medium', 'High', 'Critical'];
const SEVERITY_COLORS = {
  Low:      { bg: '#00c853', text: '#fff' },
  Medium:   { bg: '#ffc107', text: '#000' },
  High:     { bg: '#ff6d00', text: '#fff' },
  Critical: { bg: '#cc0000', text: '#fff' },
};

const buildSeverityStages = (severity) => {
  const activeIndex = SEVERITY_STAGES.indexOf(severity);
  const colors = SEVERITY_COLORS[severity] || SEVERITY_COLORS.High;
  const stages = SEVERITY_STAGES.map((stage, i) => {
    const isActive = i === activeIndex;
    const isPast   = i < activeIndex;
    const sc       = SEVERITY_COLORS[stage];
    const bg       = isActive ? sc.bg : isPast ? `${sc.bg}66` : '#e0e0e0';
    const tc       = isActive ? sc.text : isPast ? '#555' : '#bbb';
    return `<div style="flex:1;text-align:center;padding:8px 4px;border-radius:8px;background:${bg};color:${tc};font-weight:${isActive?900:600};font-size:${isActive?13:11}px;border:${isActive?`2px solid ${sc.bg}`:'2px solid transparent'};">${isActive?`<div style="font-size:8px;font-weight:900;letter-spacing:1px;margin-bottom:2px;">▼ CURRENT</div>`:''}${stage.toUpperCase()}</div>`;
  });
  return `<div style="display:flex;gap:5px;margin-top:6px;">${stages.join('')}</div><div style="margin-top:6px;font-size:11px;color:#555;">Classified as <strong style="color:${colors.bg};">${severity} Priority</strong></div>`;
};

// ── Main HTML builder ────────────────────────────────────────────────────────
const buildFIRHTML = (fir) => {
  const lang = fir.language || 'en';
  const L = LABELS[lang] || LABELS.en;

  const evidenceItems = (fir.evidenceList || []).map(
    (item, i) => `<tr><td style="padding:5px 8px;border-bottom:1px solid #eee;color:#777;font-size:12px;">${i+1}.</td><td style="padding:5px 8px;border-bottom:1px solid #eee;font-size:12px;">${item}</td></tr>`
  ).join('');

  const timelineItems = (fir.timeline || []).map(
    (t) => `<div style="display:flex;margin-bottom:8px;align-items:flex-start;"><div style="background:#cc0000;color:#fff;padding:3px 9px;border-radius:10px;font-size:11px;font-weight:700;white-space:nowrap;margin-right:10px;">${t.time}</div><div style="flex:1;color:#333;font-size:12px;padding-top:2px;">${t.event}</div></div>`
  ).join('');

  const sections = (fir.sectionsApplicable || []).map(
    (s) => `<span style="background:#fff3cd;border:1px solid #ffc107;color:#856404;padding:2px 7px;border-radius:4px;font-size:11px;margin-right:5px;display:inline-block;margin-bottom:3px;">${s}</span>`
  ).join('');

  const severityHTML = buildSeverityStages(fir.severity || 'Medium');

  // ── Video block (compact) ──────────────────────────────────────────────────
  const videoBlock = (fir.videoUri || fir.videoUrl) ? `
  <div class="section">
    <div class="section-title">${L.videoTitle}</div>
    <div class="section-body" style="padding:12px 16px;">
      ${fir.videoUrl ? `
      <a href="${fir.videoUrl}" style="display:block;text-decoration:none;margin-bottom:10px;">
        <div style="background:linear-gradient(135deg,#cc0000,#ff4444);border-radius:10px;padding:14px 16px;display:flex;align-items:center;gap:12px;">
          <div style="background:rgba(255,255,255,0.22);width:44px;height:44px;border-radius:22px;display:flex;align-items:center;justify-content:center;font-size:24px;flex-shrink:0;">▶</div>
          <div style="flex:1;"><div style="color:#fff;font-weight:900;font-size:14px;margin-bottom:3px;">${L.playBtn}</div><div style="color:rgba(255,255,255,0.8);font-size:10px;word-break:break-all;">${fir.videoUrl}</div></div>
          <div style="background:#fff;color:#cc0000;padding:5px 10px;border-radius:6px;font-size:11px;font-weight:900;">${L.playLabel}</div>
        </div>
      </a>
      <div style="background:#f8f9fa;border:1px dashed #ccc;border-radius:6px;padding:7px 10px;margin-bottom:8px;"><div style="font-size:9px;color:#888;font-weight:700;text-transform:uppercase;letter-spacing:0.6px;margin-bottom:2px;">${L.copyUrl}</div><div style="font-family:monospace;font-size:10px;color:#1565c0;word-break:break-all;font-weight:700;">${fir.videoUrl}</div><div style="font-size:9px;color:#aaa;margin-top:2px;">${L.permanent}</div></div>
      ` : `<div style="background:#fff3cd;border:1px solid #ffc107;border-radius:6px;padding:10px 12px;margin-bottom:8px;"><div style="color:#856404;font-size:12px;">⚠️ Video recorded locally. Cloud upload not completed.</div></div>`}
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:6px;"><div><div style="font-size:9px;color:#888;font-weight:700;text-transform:uppercase;">Recorded At</div><div style="font-size:12px;color:#222;margin-top:2px;">${fir.incidentTime}</div></div><div><div style="font-size:9px;color:#888;font-weight:700;text-transform:uppercase;">GPS</div><div style="font-size:12px;color:#222;margin-top:2px;">${fir.location?.latitude?.toFixed(5)}, ${fir.location?.longitude?.toFixed(5)}</div></div></div>
      <div style="display:flex;gap:6px;flex-wrap:wrap;"><span style="background:#1a1a2e;color:#ffa500;padding:2px 8px;border-radius:3px;font-size:10px;font-weight:700;">${L.geoTagged}</span><span style="background:#1a1a2e;color:#00c853;padding:2px 8px;border-radius:3px;font-size:10px;font-weight:700;">${L.timestamped}</span><span style="background:#1a1a2e;color:#2196f3;padding:2px 8px;border-radius:3px;font-size:10px;font-weight:700;">${L.aiVerified}</span>${fir.videoUrl ? `<span style="background:#cc0000;color:#fff;padding:2px 8px;border-radius:3px;font-size:10px;font-weight:700;">${L.online}</span>` : ''}</div>
    </div>
  </div>` : '';

  // ── Plate photo block — always show if photo was taken ─────────────────────
  const platePhotoBlock = fir.hasPlatePhoto ? `
  <div class="section">
    <div class="section-title">${L.plateTitle}</div>
    <div class="section-body" style="padding:12px 16px;">
      <div style="text-align:center;background:#f5f5f5;border-radius:8px;padding:10px;border:2px dashed #1a1a2e;margin-bottom:8px;">
        ${fir.platePhotoDataUri
          ? `<img src="${fir.platePhotoDataUri}" style="max-width:100%;max-height:220px;border-radius:6px;object-fit:contain;border:2px solid #1a1a2e;" alt="Number Plate Photo" />`
          : `<div style="padding:20px;color:#888;font-size:13px;">📸 Number plate photo was captured.<br/>Vehicle: <strong style="color:#cc0000;">${fir.vehicleNumber || 'Recorded'}</strong></div>`
        }
        <div style="font-size:10px;color:#888;margin-top:6px;">📸 Vehicle: <strong style="color:#cc0000;">${fir.vehicleNumber || 'See plate above'}</strong></div>
      </div>
      <div style="display:flex;gap:6px;"><span style="background:#1565c0;color:#fff;padding:2px 8px;border-radius:3px;font-size:10px;font-weight:700;">PHOTO EVIDENCE</span><span style="background:#1a1a2e;color:#ffa500;padding:2px 8px;border-radius:3px;font-size:10px;font-weight:700;">${L.timestamped}</span><span style="background:#1a1a2e;color:#00c853;padding:2px 8px;border-radius:3px;font-size:10px;font-weight:700;">${L.geoTagged}</span></div>
    </div>
  </div>` : '';


  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>FIR - ${fir.referenceNumber}</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Arial',sans-serif; background:#f5f5f5; color:#222; font-size:13px; }
  .page { width:794px; margin:0 auto; background:#fff; }
  .header { background:linear-gradient(135deg,#1a1a2e 0%,#16213e 60%,#cc0000 100%); padding:22px 36px; color:white; }
  .header-top { display:flex; justify-content:space-between; align-items:center; margin-bottom:14px; }
  .logo-text { font-size:36px; font-weight:900; letter-spacing:2px; }
  .logo-sub { font-size:11px; opacity:0.85; letter-spacing:1px; margin-top:2px; }
  .fir-title { font-size:18px; font-weight:700; letter-spacing:2px; border:2px solid rgba(255,255,255,0.4); padding:6px 18px; border-radius:4px; }
  .ref-badge { background:rgba(255,165,0,0.9); color:#000; padding:6px 14px; border-radius:16px; font-weight:800; font-size:14px; }
  .content { padding:20px 36px; }
  .section { margin-bottom:14px; border:1px solid #e0e0e0; border-radius:7px; overflow:hidden; }
  .section-title { background:#1a1a2e; color:white; padding:8px 14px; font-size:11px; font-weight:700; letter-spacing:1px; text-transform:uppercase; }
  .section-body { padding:14px; }
  .grid-2 { display:grid; grid-template-columns:1fr 1fr; gap:10px; }
  .field { margin-bottom:8px; }
  .field-label { font-size:9px; color:#888; font-weight:700; text-transform:uppercase; letter-spacing:0.5px; }
  .field-value { font-size:13px; color:#222; font-weight:500; margin-top:2px; }
  .severity-badge { padding:3px 12px; border-radius:10px; font-size:12px; font-weight:800; display:inline-block; }
  .severity-Critical { background:#cc0000; color:white; }
  .severity-High { background:#ff6d00; color:white; }
  .severity-Medium { background:#ffc107; color:#000; }
  .severity-Low { background:#00c853; color:white; }
  .statement { background:#f9f9f9; border-left:4px solid #cc0000; padding:10px 14px; font-size:12px; line-height:1.65; color:#333; border-radius:0 4px 4px 0; }
  table { width:100%; border-collapse:collapse; }
  .footer { background:#1a1a2e; color:rgba(255,255,255,0.8); padding:14px 36px; font-size:10px; display:flex; justify-content:space-between; align-items:center; }
  .ai-badge { background:linear-gradient(135deg,#cc0000,#ff4444); color:white; padding:4px 12px; border-radius:16px; font-size:11px; font-weight:700; }
  .verified { display:inline-block; border:2px solid #00c853; color:#00c853; padding:2px 8px; border-radius:4px; font-size:10px; font-weight:700; }
</style>
</head>
<body>
<div class="page">

  <!-- SUBMITTED STAMP (compact) -->
  <div style="padding:8px 36px;background:#e8f5e9;border-bottom:2px solid #00c853;display:flex;align-items:center;gap:10px;">
    <div style="font-size:18px;">✉️</div>
    <div style="flex:1;"><div style="font-weight:800;color:#1b5e20;font-size:12px;">${L.firSubmitted}</div><div style="color:#2e7d32;font-size:11px;">Ref: <strong>${fir.referenceNumber}</strong> &nbsp;|&nbsp; ${fir.policeStation}</div></div>
    <div style="background:#00c853;color:#fff;padding:4px 10px;border-radius:12px;font-size:10px;font-weight:800;white-space:nowrap;">✓ FILED</div>
  </div>

  <!-- HEADER -->
  <div class="header">
    <div class="header-top">
      <div><div class="logo-text">⚡ SAHAAS</div><div class="logo-sub">${L.subtitle}</div></div>
      <div style="text-align:center;"><div class="fir-title">${L.title}</div></div>
      <div class="ref-badge">${fir.referenceNumber}</div>
    </div>
    <div style="display:flex;justify-content:space-between;align-items:center;border-top:1px solid rgba(255,255,255,0.2);padding-top:10px;">
      <div style="font-size:11px;opacity:0.9;">📍 ${fir.policeStation}, ${fir.district}, ${fir.state}</div>
      <div style="font-size:11px;opacity:0.9;">🕐 ${fir.filedAtFormatted}</div>
      <div class="verified">✓ AI VERIFIED</div>
    </div>
  </div>

  <div class="content">

    <!-- INCIDENT OVERVIEW -->
    <div class="section">
      <div class="section-title">${L.overview}</div>
      <div class="section-body">
        <div class="grid-2">
          <div class="field"><div class="field-label">${L.incidentType}</div><div class="field-value">${fir.incidentType}</div></div>
          <div class="field"><div class="field-label">${L.dateTime}</div><div class="field-value">${fir.incidentTime}</div></div>
        </div>
        <div class="field" style="margin-top:8px;">
          <div class="field-label">${L.severity}</div>
          <div style="margin-top:3px;"><span class="severity-badge severity-${fir.severity}">${fir.severity?.toUpperCase()}</span></div>
          ${severityHTML}
        </div>
        <div class="field" style="margin-top:10px;">
          <div class="field-label">${L.summary}</div>
          <div class="statement" style="margin-top:4px;">${fir.summary}</div>
        </div>
      </div>
    </div>

    <!-- LOCATION + DETAILS (combined row to save space) -->
    <div class="grid-2" style="gap:14px;margin-bottom:14px;">
      <div class="section" style="margin-bottom:0;">
        <div class="section-title">${L.location}</div>
        <div class="section-body">
          <div class="field"><div class="field-label">${L.address}</div><div class="field-value">${fir.location?.address || 'Recorded'}</div></div>
          <div class="field"><div class="field-label">${L.gps}</div><div class="field-value" style="font-family:monospace;font-size:12px;">${fir.location?.latitude?.toFixed(5)}, ${fir.location?.longitude?.toFixed(5)}</div></div>
          <div class="field"><div class="field-label">${L.maps}</div><div class="field-value" style="color:#1565c0;font-size:11px;word-break:break-all;">${fir.location?.googleMapsUrl}</div></div>
        </div>
      </div>
      <div class="section" style="margin-bottom:0;">
        <div class="section-title">${L.details}</div>
        <div class="section-body">
          <div class="field"><div class="field-label">${L.injuries}</div><div class="field-value" style="color:${fir.injured?'#cc0000':'#00c853'};font-weight:700;font-size:12px;">${fir.injured?'⚠️ YES — Needed':'✅ None Reported'}</div></div>
          <div class="field"><div class="field-label">${L.vehicle}</div><div class="field-value" style="font-family:monospace;font-size:14px;background:#f0f0f0;padding:2px 6px;border-radius:4px;display:inline-block;">${fir.vehicleNumber}</div></div>
          <div class="field"><div class="field-label">${L.people}</div><div class="field-value">${fir.peopleCount} person(s)</div></div>
          <div class="field"><div class="field-label">${L.witnesses}</div><div class="field-value">${fir.witnesses}</div></div>
        </div>
      </div>
    </div>

    <!-- TIMELINE + STATEMENT (side by side) -->
    <div class="grid-2" style="gap:14px;margin-bottom:14px;">
      <div class="section" style="margin-bottom:0;">
        <div class="section-title">${L.timeline}</div>
        <div class="section-body">${timelineItems || '<p style="color:#888;font-size:12px;">AI generated</p>'}</div>
      </div>
      <div class="section" style="margin-bottom:0;">
        <div class="section-title">${L.statement}</div>
        <div class="section-body">
          <div class="statement" style="font-size:11px;">"${fir.complainantStatement}"</div>
          <div style="margin-top:8px;"><div class="field-label">${L.sections}</div><div style="margin-top:4px;">${sections}</div></div>
        </div>
      </div>
    </div>

    <!-- VIDEO EVIDENCE -->
    ${videoBlock}

    <!-- PLATE PHOTO EVIDENCE -->
    ${platePhotoBlock}

    <!-- EVIDENCE LIST -->
    <div class="section">
      <div class="section-title">${L.evidence}</div>
      <div class="section-body" style="padding:10px 14px;"><table>${evidenceItems}</table></div>
    </div>

    <!-- AI INSIGHTS -->
    <div class="section">
      <div class="section-title">${L.ai}</div>
      <div class="section-body">
        <div class="statement" style="font-size:12px;">${fir.aiInsights}</div>
        <div style="margin-top:8px;display:flex;align-items:center;gap:8px;">
          <span class="ai-badge">AI GENERATED</span>
          <span style="font-size:11px;color:#888;">${L.generated} ${fir.filedAtFormatted}</span>
        </div>
      </div>
    </div>

  </div>

  <!-- FOOTER -->
  <div class="footer">
    <div><div style="font-weight:700;margin-bottom:2px;">SAHAAS — संकट में सहायता</div><div>${L.policeFooter}</div></div>
    <div style="text-align:center;"><div style="font-size:16px;font-weight:800;color:#ffa500;">${fir.referenceNumber}</div><div>${L.firRef}</div></div>
    <div style="text-align:right;"><div>${L.digital}</div><div>${L.submitted} ${fir.submittedVia}</div></div>
  </div>

</div>
</body>
</html>`;
};
