// â”€â”€â”€ SAHAAS CONSTANTS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

// SOTE AI - Incident analysis service
// API endpoint configured through environment
// API key loaded from local environment
export const SOTE_API_URL = process.env.EXPO_PUBLIC_SOTE_API_URL || 'https://soteai.onrender.com';
export const SOTE_API_KEY = process.env.EXPO_PUBLIC_SOTE_API_KEY || '';






// Cloudinary â€” for video uploads (free account at cloudinary.com)
// Steps: 1) Sign up free at cloudinary.com  2) Copy your Cloud Name below
//        3) Settings â†’ Upload â†’ Add Preset â†’ Unsigned â†’ name it 'sahaas_videos'
export const CLOUDINARY_CLOUD_NAME = process.env.EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME || '';
export const CLOUDINARY_UPLOAD_PRESET = process.env.EXPO_PUBLIC_CLOUDINARY_UPLOAD_PRESET || '';

// Emergency contacts (for demo â€” real numbers to your friend's phone)
export const EMERGENCY_CONTACTS = {
  police: process.env.EXPO_PUBLIC_POLICE_PHONE || '',
  ambulance: process.env.EXPO_PUBLIC_AMBULANCE_PHONE || '',
  fire: process.env.EXPO_PUBLIC_FIRE_PHONE || '',
};

// Email config
export const EMAIL_CONFIG = {
  serviceId: process.env.EXPO_PUBLIC_EMAIL_SERVICE_ID || '',
  templateId: process.env.EXPO_PUBLIC_EMAIL_TEMPLATE_ID || '',
  publicKey: process.env.EXPO_PUBLIC_EMAIL_PUBLIC_KEY || '',
  toEmail: process.env.EXPO_PUBLIC_EMAIL_TO || '',
};

// Fast2SMS
export const SMS_API_KEY = process.env.EXPO_PUBLIC_SMS_API_KEY || '';

export const APP_CONFIG = {
  name: 'Sahaas',
  nameHindi: 'à¤¸à¤¹à¤¾à¤¸',
  nameTelugu: 'à°¸à°¹à°¾à°¸à±',
  nameGujarati: 'àª¸àª¹àª¾àª¸',
  city: 'Hyderabad',
  state: 'Telangana',
  policeStation: 'Hyderabad City Police Control Room',
  pcr: 'PCR-100',
  version: '1.0.0',
};

export const COLORS = {
  primary: '#CC0000',       // Deep red - emergency
  primaryDark: '#8B0000',
  primaryLight: '#FF4444',
  secondary: '#1A1A2E',     // Deep navy
  secondaryLight: '#16213E',
  accent: '#FFA500',        // Urgent amber
  accentLight: '#FFD700',
  success: '#00C853',
  warning: '#FF6D00',
  white: '#FFFFFF',
  offWhite: '#F8F9FA',
  lightGray: '#E0E0E0',
  darkGray: '#424242',
  black: '#000000',
  overlay: 'rgba(0,0,0,0.7)',
  cardBg: 'rgba(255,255,255,0.05)',
};

export const LANGUAGES = {
  en: 'English',
  hi: 'à¤¹à¤¿à¤‚à¤¦à¥€',
  te: 'à°¤à±†à°²à±à°—à±',
  gu: 'àª—à«àªœàª°àª¾àª¤à«€',
};

export const STRINGS = {
  en: {
    appTagline: 'Emergency Incident Response',
    captureButton: 'CAPTURE INCIDENT',
    recordingFor: 'Recording for',
    seconds: 'seconds',
    stopRecording: 'Stop & Continue',
    question1: 'Is anyone injured?',
    question2: 'Vehicle Number (if any)',
    question3: 'Number of people involved',
    question4: 'Describe what happened',
    analyzing: 'SOTE AI is analyzing the incident...',
    generatingFIR: 'Generating FIR...',
    firReady: 'FIR Ready',
    downloadPDF: 'Download PDF',
    sendEmail: 'Email FIR',
    dispatchHelp: 'Dispatch Emergency Help',
  police: process.env.EXPO_PUBLIC_POLICE_PHONE || '',
  ambulance: process.env.EXPO_PUBLIC_AMBULANCE_PHONE || '',
    fireBrigade: 'Ambulance + Fire',
    calling: 'Connecting...',
    dispatched: 'Help Dispatched!',
    yes: 'Yes',
    no: 'No',
    enterVehicle: 'e.g. TS 09 AB 1234',
    enterDescription: 'Describe the incident in detail...',
    analyzeAI: 'Analyze with AI â†’',
    location: 'Location',
    dateTime: 'Date & Time',
    firNumber: 'FIR Reference',
    howItWorks: 'How It Works',
    step1: 'Open app, tap Capture',
    step2: 'Record 10-30 sec video',
    step3: 'Answer 4 quick questions',
    step4: 'AI generates FIR instantly',
    step5: 'Dispatch police/ambulance',
    incidentType: 'Incident Type',
    severity: 'Severity',
    summary: 'Summary',
    dispatchedMsg: 'Emergency help has been dispatched',
    callPolice: 'Call Police',
    callAmbulance: 'Call Ambulance',
    capturePhoto: 'Capture Number Plate (Optional)',
    skipPhoto: 'Skip & Continue',
    retake: 'Retake',
    usePhoto: 'Use This Photo',
    stepProcessing: 'Processing geo-tagged video...',
    stepGPS: 'Extracting GPS coordinates...',
    stepTimestamp: 'Verifying timestamp & evidence...',
    stepSoteAI: 'Running SOTE AI incident analysis...',
    stepFIR: 'Generating FIR document...',
    stepFinalise: 'Finalising report...',
  },
  hi: {
    appTagline: 'à¤†à¤ªà¤¾à¤¤à¤•à¤¾à¤²à¥€à¤¨ à¤˜à¤Ÿà¤¨à¤¾ à¤ªà¥à¤°à¤¤à¤¿à¤•à¥à¤°à¤¿à¤¯à¤¾',
    captureButton: 'à¤˜à¤Ÿà¤¨à¤¾ à¤°à¤¿à¤•à¥‰à¤°à¥à¤¡ à¤•à¤°à¥‡à¤‚',
    recordingFor: 'à¤°à¤¿à¤•à¥‰à¤°à¥à¤¡à¤¿à¤‚à¤—',
    seconds: 'à¤¸à¥‡à¤•à¤‚à¤¡',
    stopRecording: 'à¤°à¥‹à¤•à¥‡à¤‚ à¤”à¤° à¤œà¤¾à¤°à¥€ à¤°à¤–à¥‡à¤‚',
    question1: 'à¤•à¥à¤¯à¤¾ à¤•à¥‹à¤ˆ à¤˜à¤¾à¤¯à¤² à¤¹à¥ˆ?',
    question2: 'à¤µà¤¾à¤¹à¤¨ à¤¨à¤‚à¤¬à¤° (à¤¯à¤¦à¤¿ à¤¹à¥‹)',
    question3: 'à¤¶à¤¾à¤®à¤¿à¤² à¤²à¥‹à¤—à¥‹à¤‚ à¤•à¥€ à¤¸à¤‚à¤–à¥à¤¯à¤¾',
    question4: 'à¤•à¥à¤¯à¤¾ à¤¹à¥à¤† à¤¬à¤¤à¤¾à¤à¤‚',
    analyzing: 'SOTE AI à¤˜à¤Ÿà¤¨à¤¾ à¤•à¤¾ à¤µà¤¿à¤¶à¥à¤²à¥‡à¤·à¤£ à¤•à¤° à¤°à¤¹à¤¾ à¤¹à¥ˆ...',
    generatingFIR: 'FIR à¤¬à¤¨à¤¾ à¤°à¤¹à¥‡ à¤¹à¥ˆà¤‚...',
    firReady: 'FIR à¤¤à¥ˆà¤¯à¤¾à¤° à¤¹à¥ˆ',
    downloadPDF: 'PDF à¤¡à¤¾à¤‰à¤¨à¤²à¥‹à¤¡ à¤•à¤°à¥‡à¤‚',
    sendEmail: 'FIR à¤ˆà¤®à¥‡à¤² à¤•à¤°à¥‡à¤‚',
    dispatchHelp: 'à¤†à¤ªà¤¾à¤¤à¤•à¤¾à¤²à¥€à¤¨ à¤¸à¤¹à¤¾à¤¯à¤¤à¤¾ à¤­à¥‡à¤œà¥‡à¤‚',
  police: process.env.EXPO_PUBLIC_POLICE_PHONE || '',
  ambulance: process.env.EXPO_PUBLIC_AMBULANCE_PHONE || '',
    fireBrigade: 'à¤à¤®à¥à¤¬à¥à¤²à¥‡à¤‚à¤¸ + à¤…à¤—à¥à¤¨à¤¿à¤¶à¤®à¤¨',
    calling: 'à¤œà¥‹à¤¡à¤¼à¤¾ à¤œà¤¾ à¤°à¤¹à¤¾ à¤¹à¥ˆ...',
    dispatched: 'à¤¸à¤¹à¤¾à¤¯à¤¤à¤¾ à¤­à¥‡à¤œà¥€ à¤—à¤ˆ!',
    yes: 'à¤¹à¤¾à¤',
    no: 'à¤¨à¤¹à¥€à¤‚',
    enterVehicle: 'à¤œà¥ˆà¤¸à¥‡ TS 09 AB 1234',
    enterDescription: 'à¤˜à¤Ÿà¤¨à¤¾ à¤•à¤¾ à¤µà¤¿à¤µà¤°à¤£ à¤¦à¥‡à¤‚...',
    analyzeAI: 'AI à¤¸à¥‡ à¤µà¤¿à¤¶à¥à¤²à¥‡à¤·à¤£ à¤•à¤°à¥‡à¤‚ â†’',
    location: 'à¤¸à¥à¤¥à¤¾à¤¨',
    dateTime: 'à¤¦à¤¿à¤¨à¤¾à¤‚à¤• à¤”à¤° à¤¸à¤®à¤¯',
    firNumber: 'FIR à¤¸à¤‚à¤¦à¤°à¥à¤­',
    howItWorks: 'à¤¯à¤¹ à¤•à¥ˆà¤¸à¥‡ à¤•à¤¾à¤® à¤•à¤°à¤¤à¤¾ à¤¹à¥ˆ',
    step1: 'à¤à¤ª à¤–à¥‹à¤²à¥‡à¤‚, à¤•à¥ˆà¤ªà¥à¤šà¤° à¤Ÿà¥ˆà¤ª à¤•à¤°à¥‡à¤‚',
    step2: '10-30 à¤¸à¥‡à¤•à¤‚à¤¡ à¤µà¥€à¤¡à¤¿à¤¯à¥‹ à¤°à¤¿à¤•à¥‰à¤°à¥à¤¡ à¤•à¤°à¥‡à¤‚',
    step3: '4 à¤ªà¥à¤°à¤¶à¥à¤¨à¥‹à¤‚ à¤•à¤¾ à¤‰à¤¤à¥à¤¤à¤° à¤¦à¥‡à¤‚',
    step4: 'AI à¤¤à¥à¤°à¤‚à¤¤ FIR à¤¤à¥ˆà¤¯à¤¾à¤° à¤•à¤°à¤¤à¤¾ à¤¹à¥ˆ',
    step5: 'à¤ªà¥à¤²à¤¿à¤¸/à¤à¤®à¥à¤¬à¥à¤²à¥‡à¤‚à¤¸ à¤­à¥‡à¤œà¥‡à¤‚',
    incidentType: 'à¤˜à¤Ÿà¤¨à¤¾ à¤•à¤¾ à¤ªà¥à¤°à¤•à¤¾à¤°',
    severity: 'à¤—à¤‚à¤­à¥€à¤°à¤¤à¤¾',
    summary: 'à¤¸à¤¾à¤°à¤¾à¤‚à¤¶',
    dispatchedMsg: 'à¤†à¤ªà¤¾à¤¤à¤•à¤¾à¤²à¥€à¤¨ à¤¸à¤¹à¤¾à¤¯à¤¤à¤¾ à¤­à¥‡à¤œà¥€ à¤—à¤ˆ',
    callPolice: 'à¤ªà¥à¤²à¤¿à¤¸ à¤•à¥‹ à¤•à¥‰à¤² à¤•à¤°à¥‡à¤‚',
    callAmbulance: 'à¤à¤®à¥à¤¬à¥à¤²à¥‡à¤‚à¤¸ à¤•à¥‹ à¤•à¥‰à¤² à¤•à¤°à¥‡à¤‚',
    capturePhoto: 'à¤¨à¤‚à¤¬à¤° à¤ªà¥à¤²à¥‡à¤Ÿ à¤«à¥‹à¤Ÿà¥‹ (à¤µà¥ˆà¤•à¤²à¥à¤ªà¤¿à¤•)',
    skipPhoto: 'à¤›à¥‹à¤¡à¤¼à¥‡à¤‚ à¤”à¤° à¤œà¤¾à¤°à¥€ à¤°à¤–à¥‡à¤‚',
    retake: 'à¤«à¤¿à¤° à¤¸à¥‡ à¤²à¥‡à¤‚',
    usePhoto: 'à¤¯à¤¹ à¤«à¥‹à¤Ÿà¥‹ à¤‰à¤ªà¤¯à¥‹à¤— à¤•à¤°à¥‡à¤‚',
    stepProcessing: 'à¤œà¤¿à¤¯à¥‹-à¤Ÿà¥ˆà¤—à¥à¤¡ à¤µà¥€à¤¡à¤¿à¤¯à¥‹ à¤ªà¥à¤°à¥‹à¤¸à¥‡à¤¸ à¤¹à¥‹ à¤°à¤¹à¤¾ à¤¹à¥ˆ...',
    stepGPS: 'GPS à¤¨à¤¿à¤°à¥à¤¦à¥‡à¤¶à¤¾à¤‚à¤• à¤¨à¤¿à¤•à¤¾à¤² à¤°à¤¹à¥‡ à¤¹à¥ˆà¤‚...',
    stepTimestamp: 'à¤Ÿà¤¾à¤‡à¤®à¤¸à¥à¤Ÿà¥ˆà¤®à¥à¤ª à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¿à¤¤ à¤¹à¥‹ à¤°à¤¹à¤¾ à¤¹à¥ˆ...',
    stepSoteAI: 'SOTE AI à¤µà¤¿à¤¶à¥à¤²à¥‡à¤·à¤£ à¤šà¤² à¤°à¤¹à¤¾ à¤¹à¥ˆ...',
    stepFIR: 'FIR à¤¦à¤¸à¥à¤¤à¤¾à¤µà¥‡à¤œà¤¼ à¤¬à¤¨ à¤°à¤¹à¤¾ à¤¹à¥ˆ...',
    stepFinalise: 'à¤°à¤¿à¤ªà¥‹à¤°à¥à¤Ÿ à¤…à¤‚à¤¤à¤¿à¤® à¤¹à¥‹ à¤°à¤¹à¥€ à¤¹à¥ˆ...',
  },
  te: {
    appTagline: 'à°…à°¤à±à°¯à°µà°¸à°° à°¸à°‚à°˜à°Ÿà°¨ à°¸à±à°ªà°‚à°¦à°¨',
    captureButton: 'à°¸à°‚à°˜à°Ÿà°¨ à°°à°¿à°•à°¾à°°à±à°¡à± à°šà±‡à°¯à°¿',
    recordingFor: 'à°°à°¿à°•à°¾à°°à±à°¡à°¿à°‚à°—à±',
    seconds: 'à°¸à±†à°•à°¨à±à°²à±',
    stopRecording: 'à°†à°ªà°¿ à°•à±Šà°¨à°¸à°¾à°—à°¿à°‚à°šà±',
    question1: 'à°Žà°µà°°à±ˆà°¨à°¾ à°—à°¾à°¯à°ªà°¡à±à°¡à°¾à°°à°¾?',
    question2: 'à°µà°¾à°¹à°¨ à°¨à°‚à°¬à°°à± (à°à°¦à±ˆà°¨à°¾ à°‰à°‚à°Ÿà±‡)',
    question3: 'à°ªà°¾à°²à±à°—à±Šà°¨à±à°¨ à°µà±à°¯à°•à±à°¤à±à°² à°¸à°‚à°–à±à°¯',
    question4: 'à°à°®à°¿ à°œà°°à°¿à°—à°¿à°‚à°¦à±‹ à°µà°¿à°µà°°à°¿à°‚à°šà°‚à°¡à°¿',
    analyzing: 'SOTE AI à°¸à°‚à°˜à°Ÿà°¨à°¨à± à°µà°¿à°¶à±à°²à±‡à°·à°¿à°¸à±à°¤à±‹à°‚à°¦à°¿...',
    generatingFIR: 'FIR à°°à±‚à°ªà±Šà°‚à°¦à°¿à°¸à±à°¤à±‹à°‚à°¦à°¿...',
    firReady: 'FIR à°¸à°¿à°¦à±à°§à°‚à°—à°¾ à°‰à°‚à°¦à°¿',
    downloadPDF: 'PDF à°¡à±Œà°¨à±â€Œà°²à±‹à°¡à±',
    sendEmail: 'FIR à°‡à°®à±†à°¯à°¿à°²à±',
    dispatchHelp: 'à°…à°¤à±à°¯à°µà°¸à°° à°¸à°¹à°¾à°¯à°‚ à°ªà°‚à°ªà°‚à°¡à°¿',
  police: process.env.EXPO_PUBLIC_POLICE_PHONE || '',
  ambulance: process.env.EXPO_PUBLIC_AMBULANCE_PHONE || '',
    fireBrigade: 'à°…à°‚à°¬à±à°²à±†à°¨à±à°¸à± + à°…à°—à±à°¨à°¿à°®à°¾à°ªà°•',
    calling: 'à°•à°¨à±†à°•à±à°Ÿà± à°…à°µà±à°¤à±‹à°‚à°¦à°¿...',
    dispatched: 'à°¸à°¹à°¾à°¯à°‚ à°ªà°‚à°ªà°¬à°¡à°¿à°‚à°¦à°¿!',
    yes: 'à°…à°µà±à°¨à±',
    no: 'à°•à°¾à°¦à±',
    enterVehicle: 'à°‰à°¦à°¾. TS 09 AB 1234',
    enterDescription: 'à°¸à°‚à°˜à°Ÿà°¨ à°—à±à°°à°¿à°‚à°šà°¿ à°µà°¿à°µà°°à°‚à°—à°¾ à°šà±†à°ªà±à°ªà°‚à°¡à°¿...',
    analyzeAI: 'AI à°¤à±‹ à°µà°¿à°¶à±à°²à±‡à°·à°¿à°‚à°šà± â†’',
    location: 'à°¸à±à°¥à°¾à°¨à°‚',
    dateTime: 'à°¤à±‡à°¦à±€ & à°¸à°®à°¯à°‚',
    firNumber: 'FIR à°¸à±‚à°šà°¨',
    howItWorks: 'à°‡à°¦à°¿ à°Žà°²à°¾ à°ªà°¨à°¿ à°šà±‡à°¸à±à°¤à±à°‚à°¦à°¿',
    step1: 'à°¯à°¾à°ªà± à°¤à±†à°°à°µà°‚à°¡à°¿, à°•à°¾à°ªà±à°šà°°à± à°¨à±Šà°•à±à°•à°‚à°¡à°¿',
    step2: '10-30 à°¸à±†à°•à°¨à±à°² à°µà±€à°¡à°¿à°¯à±‹ à°¤à±€à°¯à°‚à°¡à°¿',
    step3: '4 à°ªà±à°°à°¶à±à°¨à°²à°•à± à°œà°µà°¾à°¬à°¿à°µà±à°µà°‚à°¡à°¿',
    step4: 'AI à°µà±†à°‚à°Ÿà°¨à±‡ FIR à°¤à°¯à°¾à°°à±à°šà±‡à°¸à±à°¤à±à°‚à°¦à°¿',
    step5: 'à°ªà±‹à°²à±€à°¸à±/à°…à°‚à°¬à±à°²à±†à°¨à±à°¸à± à°ªà°‚à°ªà°‚à°¡à°¿',
    incidentType: 'à°¸à°‚à°˜à°Ÿà°¨ à°°à°•à°‚',
    severity: 'à°¤à±€à°µà±à°°à°¤',
    summary: 'à°¸à°¾à°°à°¾à°‚à°¶à°‚',
    dispatchedMsg: 'à°…à°¤à±à°¯à°µà°¸à°° à°¸à°¹à°¾à°¯à°‚ à°ªà°‚à°ªà°¬à°¡à°¿à°‚à°¦à°¿',
    callPolice: 'à°ªà±‹à°²à±€à°¸à±à°²à°•à± à°•à°¾à°²à± à°šà±‡à°¯à°‚à°¡à°¿',
    callAmbulance: 'à°…à°‚à°¬à±à°²à±†à°¨à±à°¸à± à°•à± à°•à°¾à°²à± à°šà±‡à°¯à°‚à°¡à°¿',
    capturePhoto: 'à°¨à°‚à°¬à°°à± à°ªà±à°²à±‡à°Ÿà± à°«à±‹à°Ÿà±‹ (à°à°šà±à°›à°¿à°•à°‚)',
    skipPhoto: 'à°¦à°¾à°Ÿà°µà±‡à°¸à°¿ à°•à±Šà°¨à°¸à°¾à°—à°¿à°‚à°šà±',
    retake: 'à°®à°³à±à°³à±€ à°¤à±€à°¯à°¿',
    usePhoto: 'à°ˆ à°«à±‹à°Ÿà±‹ à°µà°¾à°¡à±',
    stepProcessing: 'à°œà°¿à°¯à±‹-à°Ÿà±à°¯à°¾à°—à±à°¡à± à°µà±€à°¡à°¿à°¯à±‹ à°ªà±à°°à°¾à°¸à±†à°¸à±...',
    stepGPS: 'GPS à°…à°•à±à°·à°¾à°‚à°¶à°¾à°²à±...',
    stepTimestamp: 'à°Ÿà±ˆà°®à±â€Œà°¸à±à°Ÿà°¾à°‚à°ªà± à°§à±ƒà°µà±€à°•à°°à°£...',
    stepSoteAI: 'SOTE AI à°µà°¿à°¶à±à°²à±‡à°·à°£...',
    stepFIR: 'FIR à°°à±‚à°ªà±Šà°‚à°¦à±à°¤à±‹à°‚à°¦à°¿...',
    stepFinalise: 'à°¨à°¿à°µà±‡à°¦à°¿à°• à°–à°°à°¾à°°à±...',
  },
  gu: {
    appTagline: 'àª†à¤ªà¤¾à¤¤à¤•à¤¾à¤²à¥€à¤¨ àª˜àªŸàª¨àª¾ àªªà«àª°àª¤àª¿àª­àª¾àªµ',
    captureButton: 'àª˜àªŸàª¨àª¾ àª°à«‡àª•à«‹àª°à«àª¡ àª•àª°à«‹',
    recordingFor: 'àª°à«‡àª•à«‹àª°à«àª¡àª¿àª‚àª—',
    seconds: 'àª¸à«‡àª•àª¨à«àª¡',
    stopRecording: 'àª°à«‹àª•à«‹ àª…àª¨à«‡ àªšàª¾àª²à« àª°àª¾àª–à«‹',
    question1: 'àª¶à«àª‚ àª•à«‹àªˆ àª˜àª¾àª¯àª² àª›à«‡?',
    question2: 'àªµàª¾àª¹àª¨ àª¨àª‚àª¬àª° (àªœà«‹ àª¹à«‹àª¯)',
    question3: 'àª¸àª¾àª®à«‡àª² àª²à«‹àª•à«‹àª¨à«€ àª¸àª‚àª–à«àª¯àª¾',
    question4: 'àª¶à«àª‚ àª¥àª¯à«àª‚ àª¤à«‡ àªµàª°à«àª£àªµà«‹',
    analyzing: 'SOTE AI àª˜àªŸàª¨àª¾àª¨à«àª‚ àªµàª¿àª¶à«àª²à«‡àª·àª£ àª•àª°à«€ àª°àª¹à«àª¯à«àª‚ àª›à«‡...',
    generatingFIR: 'FIR àª¤à«ˆàª¯àª¾àª° àª•àª°à«€ àª°àª¹à«àª¯àª¾ àª›à«€àª...',
    firReady: 'FIR àª¤à«ˆàª¯àª¾àª° àª›à«‡',
    downloadPDF: 'PDF àª¡àª¾àª‰àª¨àª²à«‹àª¡',
    sendEmail: 'FIR àªˆ-àª®à«‡àªˆàª²',
    dispatchHelp: 'àª•àªŸà«‹àª•àªŸà«€ àª¸àª¹àª¾àª¯ àª®à«‹àª•àª²à«‹',
  police: process.env.EXPO_PUBLIC_POLICE_PHONE || '',
  ambulance: process.env.EXPO_PUBLIC_AMBULANCE_PHONE || '',
    fireBrigade: 'àªàª®à«àª¬à«àª¯à«àª²àª¨à«àª¸ + àª«àª¾àª¯àª°',
    calling: 'àª•àª¨à«‡àª•à«àªŸ àª¥àªˆ àª°àª¹à«àª¯à«àª‚ àª›à«‡...',
    dispatched: 'àª¸àª¹àª¾àª¯ àª®à«‹àª•àª²àªµàª¾àª®àª¾àª‚ àª†àªµà«€!',
    yes: 'àª¹àª¾',
    no: 'àª¨àª¾',
    enterVehicle: 'àª¦àª¾.àª¤. TS 09 AB 1234',
    enterDescription: 'àª˜àªŸàª¨àª¾ àªµàª¿àª¶à«‡ àªµàª¿àª—àª¤àªµàª¾àª° àªµàª°à«àª£àªµà«‹...',
    analyzeAI: 'AI àª¸àª¾àª¥à«‡ àªµàª¿àª¶à«àª²à«‡àª·àª£ â†’',
    location: 'àª¸à«àª¥àª³',
    dateTime: 'àª¤àª¾àª°à«€àª– & àª¸àª®àª¯',
    firNumber: 'FIR àª¸àª‚àª¦àª°à«àª­',
    howItWorks: 'àª† àª•à«‡àªµà«€ àª°à«€àª¤à«‡ àª•àª¾àª°à«àª¯ àª•àª°à«‡ àª›à«‡',
    step1: 'àªàªª àª–à«‹àª²à«‹, àª•à«‡àªªà«àªšàª° àªŸà«…àªª àª•àª°à«‹',
    step2: '10-30 àª¸à«‡àª•àª¨à«àª¡ àªµàª¿àª¡àª¿àª“ àª°à«‡àª•à«‹àª°à«àª¡',
    step3: '4 àªªà«àª°àª¶à«àª¨à«‹àª¨àª¾ àªœàªµàª¾àª¬ àª†àªªà«‹',
    step4: 'AI àª¤àª°àª¤ FIR àª¬àª¨àª¾àªµà«‡ àª›à«‡',
    step5: 'àªªà«‹àª²à«€àª¸/àªàª®à«àª¬à«àª¯à«àª²àª¨à«àª¸ àª®à«‹àª•àª²à«‹',
    incidentType: 'àª˜àªŸàª¨àª¾àª¨à«‹ àªªà«àª°àª•àª¾àª°',
    severity: 'àª—àª‚àª­à«€àª°àª¤àª¾',
    summary: 'àª¸àª¾àª°àª¾àª‚àª¶',
    dispatchedMsg: 'àª•àªŸà«‹àª•àªŸà«€ àª¸àª¹àª¾àª¯ àª®à«‹àª•àª²àªµàª¾àª®àª¾àª‚ àª†àªµà«€',
    callPolice: 'àªªà«‹àª²à«€àª¸àª¨à«‡ àª•à«‰àª² àª•àª°à«‹',
    callAmbulance: 'àªàª®à«àª¬à«àª¯à«àª²àª¨à«àª¸ àª•à«‰àª² àª•àª°à«‹',
    capturePhoto: 'àª¨àª‚àª¬àª° àªªà«àª²à«‡àªŸ àª«à«‹àªŸà«‹ (àªµà«ˆàª•àª²à«àªªàª¿àª•)',
    skipPhoto: 'àª›à«‹àª¡à«‹ àª…àª¨à«‡ àªšàª¾àª²à« àª°àª¾àª–à«‹',
    retake: 'àª«àª°à«€ àª²à«‹',
    usePhoto: 'àª† àª«à«‹àªŸà«‹ àªµàª¾àªªàª°à«‹',
    stepProcessing: 'àªœà«€àª“-àªŸà«‡àª—à«àª¡ àªµàª¿àª¡àª¿àª“ àªªà«àª°à«‹àª¸à«‡àª¸...',
    stepGPS: 'GPS àª•à«‹àª“àª°à«àª¡àª¿àª¨à«‡àªŸ...',
    stepTimestamp: 'àªŸàª¾àªˆàª®-àª¸à«àªŸà«‡àª®à«àªª àªšàª•àª¾àª¸àª£à«€...',
    stepSoteAI: 'SOTE AI àªµàª¿àª¶à«àª²à«‡àª·àª£...',
    stepFIR: 'FIR àª¡à«‰àª•à«àª¯à«àª®à«‡àª¨à«àªŸ...',
    stepFinalise: 'àª°àª¿àªªà«‹àª°à«àªŸ àª…àª‚àª¤àª¿àª®...',
  },
};
